on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v2
      - name: Shell
        shell: bash
        run: |
            env
            pwd
            ls
            cat ${GITHUB_EVENT_PATH}
